name: CI

on: [pull_request, push]

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        allow_fail: [false]
        php: [5.5, 5.6, 7.0, 7.1, 7.2, 7.3]
        include:
          - php: 7.4
            allow_fail: true
          - php: 8
            allow_fail: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
      - name: Run tests
        run: vendor/bin/phpunit test
        continue-on-error: ${{ matrix.allow_fail }}
